/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiculesRouteImport } from './routes/vehicules'
import { Route as PrestationsRouteImport } from './routes/prestations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestationsRoute = PrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/prestations': typeof PrestationsRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/prestations': typeof PrestationsRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/prestations': typeof PrestationsRoute
  '/vehicules': typeof VehiculesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/a-propos' | '/contact' | '/prestations' | '/vehicules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a-propos' | '/contact' | '/prestations' | '/vehicules'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/prestations'
    | '/vehicules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  PrestationsRoute: typeof PrestationsRoute
  VehiculesRoute: typeof VehiculesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestations': {
      id: '/prestations'
      path: '/prestations'
      fullPath: '/prestations'
      preLoaderRoute: typeof PrestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  PrestationsRoute: PrestationsRoute,
  VehiculesRoute: VehiculesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
